version: '3'


volumes:
  postgres_data_local: {}
  postgres_backup_local: {}


services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+asyncpg://money:example@postgres/money"
      JWT_SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
    ports:
      - "8000:8000"
    command: "uvicorn src.main:app --host 0.0.0.0"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: money
      POSTGRES_USER: money
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U money" ]
      interval: 5s
      timeout: 5s
      retries: 10
